### ISSUE TITLE
Add another hacktoberfest swag opportunity

### ISSUE THREAD

**Issue by arshadkazmi42** [benbarth/hacktoberfest-swag#1]
Know of another hacktoberfast swag opportunity? Add it to README.md file

**Comment by benbarth** [comment]
Done. ;)

**Comment by arshadkazmi42** [comment]
@benbarth I found one more repo which is giving away swags, let me add it to the list.

**Comment by benbarth** [comment]
Great! Thanks! Note: The list is in alphabetical order, excluding the first item.

**Comment by arshadkazmi42** [comment]
Oh. just checked Sendgrid is already there. I was about to add that repo. I don't know how i missed it there

**Comment by SoftCreatR** [comment]
I'll leave this here: https://strongloop.com/strongblog/2020-hacktoberfest/

Dunno, if they're giving out any swag.
