### ISSUE TITLE
Verify swag for 2020

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#109]
All of these items need to be **Verified 2020**!

**EDIT: Now that all of the 2019 participants are listed on the website, this list is no longer needed. Please refer to [the website](https://hacktoberfest-swag.com).**

- [x] DigitalOcean
- [ ] Accord
- [ ] Adobe / Magento
- [x] Appwrite
- [x] Aqua Security
- [x] Circle CI
- [ ] Coding Blocks
- [x] Devfolio
- [ ] Flutterwave.com
- [ ] Gatsby
- [x] Globo.com
- [x] Hasura
- [ ] JabRef
- [ ] Jenkins
- [x] Kong
- [ ] LadybugTools
- [ ] LBRY
- [ ] Les-Tilleuls.coop
- [x] MayaData
- [x] Operation Code
- [ ] Opsdroid
- [ ] Parity
- [ ] QMK
- [ ] SAP
- [x] Sense/Net
- [ ] Twilio
- [x] Uno
- [ ] Valor
- [x] Xamarin

**Comment by crweiner** [comment]
Hey @benbarth! Looking forward to a great Hacktoberfest! 🎉🎉

I know that [Appwrite is participating this year](https://github.com/crweiner/hacktoberfest-swag-list/pull/248). Working on confirming the others. 🤓

**Comment by Kolkies** [comment]
Looks like Circle CI also participates: [https://hacktoberfest.circleci.com/](https://hacktoberfest.circleci.com/)

**Comment by SoftCreatR** [comment]
Accord is participating. No info about swag yet: https://accordproject.org/events/hacktoberfest-2020/

**Comment by SoftCreatR** [comment]
Jenkins seems to participate: https://groups.google.com/g/jenkinsci-dev/c/pz3kqPnC2wA/m/EOUTnBQeAQAJ?pli=1

**Comment by SoftCreatR** [comment]
Globo seems to participate: https://opensource.globo.com/hacktoberfest/

![image](https://user-images.githubusercontent.com/81188/94640050-e2bd0b00-02dd-11eb-9259-ad9ad38dd972.png)

**Comment by SoftCreatR** [comment]
According to https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt, Kong gives out shirts not just during Hacktoberfest.

**Comment by Kolkies** [comment]
Gatsby is also doing something according to: [https://github.com/gatsbyjs/gatsby/issues/27178](https://github.com/gatsbyjs/gatsby/issues/27178)

**Comment by sanket-bhatt** [comment]
QMK is participating too. They're also celebrating their 4 year anniversary - but Hacktoberfest still applies to them. https://github.com/qmk/hacktoberfest

**Comment by SoftCreatR** [comment]
@sanket-bhatt Feel free to add them to the list / update the existing entry.

To do so, just move the file participants/2019/qmk.yml to participants/2020/qmk.yml and update it's contents, if needed.

**Comment by crweiner** [comment]
> QMK is participating too. They're also celebrating their 4 year anniversary - but Hacktoberfest still applies to them. https://github.com/qmk/hacktoberfest

Are you sure they are participating for 2020? The last commit in that repo was Oct 2019.
