### ISSUE TITLE
Add GitHub like and fork buttons

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#12]
Beside or below the current shields. Whatever looks best.

**Comment by cajuuh** [comment]
may i?

**Comment by B3v3** [comment]
Can i add this?

**Comment by benbarth** [comment]
Sure!

**Comment by B3v3** [comment]
i created buttons
`[![GitHub forks](https://img.shields.io/github/forks/badges/shields.svg?style=social&label=Fork)](https://github.com/benbarth/hacktoberfest-swag/fork)
[![GitHub stars](https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Stars)](https://github.com/benbarth/hacktoberfest-swag)`
but i have no idea how to set number of stars and forks
and normal ways to create buttons from already ready github buttons don't work in markdown preview

**Comment by benbarth** [comment]
There's an example here: https://shields.io/#/examples/social

**Comment by B3v3** [comment]
Ok, I realized how to change repo. Nevermind, I'm making a pull request now.

**Comment by benbarth** [comment]
Great work. Thanks @B3v3 !
