### ISSUE TITLE
Participants marked as sponsor appear at the top of the list

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#133]
Now that the participants list is generated automatically, it would be nice if there was an isSponsor field which moves sponsors to the top. Currently DigitalOcean is hard-coded in the script.

**Comment by jac08h** [comment]
I'd like to add this.

**Comment by SoftCreatR** [comment]
I would leave DigitalOcean at the top as initiator of the event. Whenever a new year begins, they appear on the list, while other sponsors will be announced later. However, the idea itself is good.

**Comment by sumeetmathpati** [comment]
Are you working in this?

**Comment by SoftCreatR** [comment]
Yep.
