### ISSUE TITLE
Generate page theme for contributing.md

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#134]
Currently Jekyll doesn't generate a page for contributing.md. Make contributing available from https://benbarth.github.io/hacktoberfest-swag.

**Comment by sumeetmathpati** [comment]
If I am not wrong, you want a link to the CONTRIBUTING.md page from https://benbarth.github.io/hacktoberfest-swag, right?

**Comment by SoftCreatR** [comment]
Resolved by 7c8d79134bd2c610fae2c3f939cb3297417a2dc8
