### ISSUE TITLE
.(dot) character is missing from description

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#139]
A .yml file containing the description:
Four pull requests to any public repo on GitHub. Support open source and pick a limited edition T-shirt or plant a tree.
Displays as:
Four pull requests to any public repo on GitHub. Support open source and pick a limited edition T-shirt or plant a tree

**Comment by SoftCreatR** [comment]
Well, that was purpose. However, I don't know, why I did that :D
