### ISSUE TITLE
Include GitHub repos directly in HOW section

### ISSUE THREAD

**Issue by jai-dewani** [benbarth/hacktoberfest-swag#161]
While searching for the perfect organization I can contribute to because most of the time organizations use technologies I am have not even heard about.  I faced this problem:  
- Almost all the detail is provided in the HOW section about what to do, the only reason I have to visit the Links in Additional Details is to get to the repository.  

If this information can be included directly in the HOW section will have some time for sure.  

Also if we have a column for technology that would help a lot for newbies who are comfortable in certain specific fields (*I know it will require to manually go the repositories and extract the technologies they are using*)

**Comment by benbarth** [comment]
I think the main table will be too large with more columns. I'm not opposed to another markdown page organized by language and technology. 👍

**Comment by SoftCreatR** [comment]
Well, maybe switch from Tables (I don't like them anyways) to a simpler view like in the list from @crweiner (https://github.com/crweiner/hacktoberfest-swag-list)?

**Comment by crweiner** [comment]
My reasoning for having a simple markdown list when I started the repo was twofold:
1. I just wanted a place to put the companies I was finding in a format that made sense to me.
2. If others wanted to contribute, it would be dead simple to do so. The barrier to contribute would be as nonexistent as possible.

I admire the cool yml stuff you've done with GitHub Actions, @SoftCreatR, and I think you're following in the great footsteps of @swapagarwal and DevSwag.io. He and his maintainers run a sweet project over there. 😎

A simple list works well for me and my project and I don't see myself changing that anytime soon (I'm sure other people have different opinions about how I should structure things, but I know what works for me). Other people enjoy nested tables, real CI/CD, and yml. 🤓 It's about whatever you want to maintain, who your target audience is, and whatever makes sense to *you*. 👍

**Comment by SoftCreatR** [comment]
> I admire the cool yml stuff you've done with GitHub Actions, @SoftCreatR, and I think you're following in the great footsteps of @swapagarwal and DevSwag.io. He and his maintainers run a sweet project over there. 😎

Well, I had multiple ideas on how to simplify the whole process, while making sure, that everything keeps being structured. At the end of the day, it doesn't matter, if I generate a table or a simple list, it's a simple task to modify the generation process.

My goal was to find a solution to add new participants, that is less error prone but still easy to use, even for less experienced people. And I think, the current solution is easy to use.

Using YAML, JSON or even XML allows us to validate everything by using a schema file. The problem with XML and JSON is, that their Syntax is a little bit difficult, while YAML can be used in combination with a more natural language, so everyone should be able to add new participants. Sure, it might be easier for everyone, if they could just edit the README file accordingly, but then, other things are more difficult.

Right now, everything (except for adding new participants or editing existing ones) is automated. At the beginning of a new year, the list will be reset, all participants from the last year (except for Digital Ocean) will be listed as Unverified / Past Participants and when the time has come, people can start to add new or edit existing participants, while there's no manual work involved. Even the participant blacklist stuff is partially automated.

Right now, I'm thinking about automatic archiving (e.g. automatically create a tag/release for the past year) and automatic creation of a new issue for participant validation.

And most importantly: I had the chance to learn Python :octocat:

**Comment by crweiner** [comment]
I agree! 😄 You've done some pretty sweet automation and yml is a little easier to parse for human eyes than JSON. 👍 Whatever you and @benbarth want to do I'm sure will be great!

Side note, I've got to get my Python better too. 🐍 😅

**Comment by benbarth** [comment]
@SoftCreatR is a rockstar! I've had very little exposure to GitHub actions so it's been great seeing what's possible. I normally don't love tables but being able to see all of the company names and swag icons in individual columns is valuable.

**Comment by SoftCreatR** [comment]
> @SoftCreatR is a rockstar!

In this case: https://stars.github.com/nominate

😸

**Comment by tispn** [comment]
hey let me in!

**Comment by SoftCreatR** [comment]
> hey let me in!

Not, if you don't make meaningful contributions. [This](https://github.com/benbarth/hacktoberfest-swag/pull/174) for example is by all means NOT a meaningful contribution and doesn't count towards the goal.
