### ISSUE TITLE
Add AutoDL

### ISSUE THREAD

**Issue by McTechie** [benbarth/hacktoberfest-swag#192]
Announcements:
- Twitter Tweet: https://twitter.com/auto_dl/status/1441415078494945281
- LinkedIn Post: https://www.linkedin.com/feed/update/urn:li:activity:6847191455325270016/
- Dev Blog: https://dev.to/mctechie/autodl-celebrates-hacktoberfest-2021-25da

**Comment by McTechie** [comment]
@benbarth could you assign this to me xD

**Comment by SoftCreatR** [comment]
Just create a pull request

**Comment by McTechie** [comment]
Fixed in #193
