### ISSUE TITLE
Add Flyte

### ISSUE THREAD

**Issue by SoftCreatR** [benbarth/hacktoberfest-swag#213]
https://blog.flyte.org/meet-flyte-at-hacktoberfest-2021

Just let me know if you want to take this task and I'll assign it to you.

**Comment by Kriti021999** [comment]
Can you assign it to me?

**Comment by Kriti021999** [comment]
@SoftCreatR I have created a PR, can you review it?

**Comment by SoftCreatR** [comment]
Already merged. Thank you :)
