### ISSUE TITLE
Update Switchblade

### ISSUE THREAD

**Issue by SoftCreatR** [benbarth/hacktoberfest-swag#223]
https://github.com/SwitchbladeBot/switchblade/issues/1203

Just let me know if you want to take this task and I'll assign it to you.

**Comment by RUDRANSH-hub** [comment]
i really wants to contribute in this issue will you please please assign it to me i promise i will do it with my heart.? @SoftCreatR

**Comment by SoftCreatR** [comment]
https://github.com/benbarth/hacktoberfest-swag/blob/master/CONTRIBUTING.md
