### ISSUE TITLE
Add Dev.to

### ISSUE THREAD

**Issue by SoftCreatR** [benbarth/hacktoberfest-swag#239]
https://dev.to/devteam/hacktoberfest-2021-is-here-4a3l

Whoever wants to do it: Just do it. No need to request an assignment. First come, first serve.

**Comment by devtayls** [comment]
On it!

**Comment by devtayls** [comment]
Actually, I can't exactly figure out what should go in the fields for this one. Someone else wanna take a shot?

**Comment by SoftCreatR** [comment]
I've just added a new swag type for tree planting.

Simply use `tree`, `trees`, `plant tree` or `plant trees`.
