### ISSUE TITLE
Add iconography for swag

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#25]
Add icon pack that includes icons for:
- t-shirt
- stickers
- mug
- general swag

Bonus:
- pins
- glasses
- socks  
- etc

**Comment by justinh5** [comment]
I'll give this one a shot @benbarth . I'll try to finish by tonight. Any format you want the icons?

**Comment by benbarth** [comment]
Those look great. Are they all the same size?

**Comment by justinh5** [comment]
They are approximately the same size. The difference is between 1-3 pixels with the glasses being the smallest. I can make changes if needed.

**Comment by benbarth** [comment]
I like them! Would it be possible to see them in greyscale? As well, could we add a laptop icon?

**Comment by justinh5** [comment]
I can make greyscale ones. But why? No color?? What would these be used for btw?

**Comment by benbarth** [comment]
I'd like to replace the current emojis with a standard set of icons.

**Comment by benbarth** [comment]
Ideally the icons will be roughly the same size as the inline text.

**Comment by justinh5** [comment]
Okay, just made the updates. Also made the sizes more uniform.

**Comment by benbarth** [comment]
@justinh5 did a great job.   #28   Closing.
