### ISSUE TITLE
Collaboration with swag-for-dev 💯

### ISSUE THREAD

**Issue by swapagarwal** [benbarth/hacktoberfest-swag#30]
Hello from [devSwag.io](http://devswag.io/)! 👋

We maintain a similar repository, to curate swag opportunities for developers. 😎
I think we should consolidate all swag opportunities at one place. Thoughts? 🎉

https://github.com/swapagarwal/swag-for-dev/issues/136

**Comment by arshadkazmi42** [comment]
This sounds good. I have been following both these repositories.
I have found another one
[hacktoberfest-swag-list](https://github.com/crweiner/hacktoberfest-swag-list)

**Comment by benbarth** [comment]
Sure. The more collaboration the better! I have been planning on publishing a general swag list as well. How were you thinking of collaborating? My current list is obviously focused on Hacktoberfest only items. If we came up with a "swag list JSON standard", your site could import Hacktoberfest specific items.

**Comment by benbarth** [comment]
Sure. I'd be happy to join as a collaborator. We have time to figure out how we want to promote Hacktoberfest specific items for next year.

**Comment by swapagarwal** [comment]
Awesome! Let's connect on [Twitter](http://twitter.com/SwapAgarwal) / [Telegram](https://t.me/swapagarwal). 🎉
