### ISSUE TITLE
my 4 prs are accepted and target completed yet i have not got any confirmation mail

### ISSUE THREAD

**Issue by pragatipal** [benbarth/hacktoberfest-swag#308]

**Comment by SoftCreatR** [comment]
You may check out https://hacktoberfest.digitalocean.com/profile to find out, what's the problem. Maybe, you've contributed to excluded projects, or your contributions are not mature yet. It should look like this (at least 4 marked as "completed" are required):

![image](https://user-images.githubusercontent.com/81188/139642141-c0d7b4d6-a816-47d3-9349-8c066ee8afc3.png)

**Comment by pragatipal** [comment]
> You may check out https://hacktoberfest.digitalocean.com/profile to find out, what's the problem. Maybe, you've contributed to excluded projects, or your contributions are not mature yet. It should look like this (at least 4 marked as "completed" are required):
> 
> ![image](https://user-images.githubusercontent.com/81188/139642283-c1d6e178-fa51-4d82-8d91-2800cbca208b.png)
> 
> **Total completed:**
> 
> > These pull requests have been accepted for Hacktoberfest and count toward your participation goal for Hacktoberfest. Congrats!
> 
> **In Progress:**
> 
> > These pull requests have been accepted by a maintainer and are currently in the standard 14 day review period. If they follow the values of Hacktoberfest, they’ll move to completed once this period passes for each PR.

**Comment by pragatipal** [comment]
I have completed 4 and 3 are in progress but i have also contributed to excluded projects earlier. Will that be an issue?

**Comment by SoftCreatR** [comment]
PRs in excluded projects just don't count towards the goal.

**Comment by pragatipal** [comment]
normally completed 4 prs

**Comment by SoftCreatR** [comment]
As mentioned before: At https://hacktoberfest.digitalocean.com/profile you should be able to find the reason, if there is or was any problem. Alternatively, try your luck at the official HF discord: https://discord.com/invite/hacktoberfest

**Comment by 1Alisha** [comment]
Hello sir
I have one doubt please help in that..
This year I have participated as a hacktoberfest maintainer and I have accepted many pull requests and it has been showing that my repository has been accepted for hacktoberfest but still I have not received any mail regarding swags ..

**Comment by SoftCreatR** [comment]
It takes 6 days to verify. Did you check the list at https://hacktoberfest.com/profile/?

**Comment by 1Alisha** [comment]
Yes sir I have checked but it is not showing anything..

**Comment by 1Alisha** [comment]
Yes sir I have checked but it is not showing anything..

**Comment by SoftCreatR** [comment]
What does that mean? Please share a screenshot.

**Comment by pragatipal** [comment]
Please remove me from cc

**Comment by SoftCreatR** [comment]
You can simply unsubscribe from this issue at the bottom of this page (or on the right, if you are on desktop).
