### ISSUE TITLE
2019 Version

### ISSUE THREAD

**Issue by ulgens** [benbarth/hacktoberfest-swag#31]
What about 2019 version of this list? :slightly_smiling_face: New event is coming.

**Comment by benbarth** [comment]
Yes, thank you for the reminder! This evening I started to update the page details and list. If you know of any new swag opportunities please send a PR.

**Comment by benbarth** [comment]
Some new hacktoberfest swag opportunities have been added. I'm going to add an issue to verify each 2018 item on the list.
