### ISSUE TITLE
[ADD] New Swag Opportunity - Flyte

### ISSUE THREAD

**Issue by samhita-alla** [benbarth/hacktoberfest-swag#319]
### Organization

Flyte

### Organization Website

https://flyte.org/

### Announcement URL

https://blog.flyte.org/meet-flyte-and-unionml-at-hacktoberfest-2022

### Description / Summary

Submit 2 pull requests to receive a Flyte mug; 3 pull requests to receive a Flyte t-shirt; 3+ pull requests to receive The North Face® jacket; contribute a plugin to receive a voucher. Check out https://github.com/flyteorg/flyte/issues/2917 for the available hacktoberfest-labeled issues and fill out [this form](https://tally.so/r/nWO7qQ) after the PR gets accepted/merged.

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [X] Mug
- [X] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by SoftCreatR** [comment]
Hey,

thank you for this. If you want to add it yourself, please check out the contribution guidelines: https://github.com/benbarth/hacktoberfest-swag/blob/master/CONTRIBUTING.md

If you want me to add it, just let me know :)
