### ISSUE TITLE
[ADD] New Swag Opportunity from Umbraco

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#341]
### Organization

Umbraco

### Organization Website

https://umbraco.com/

### Announcement URL

https://community.umbraco.com/get-involved/hacktoberfest/

### Description / Summary

Submit 1 PR request to get a chance to get a sticker or t-shirt.
For every contribution made to their list of select packages, they will plant a tree. https://community.umbraco.com/get-involved/plant-a-tree-with-your-contributions/

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [X] Shirt
- [ ] Socks
- [X] Stickers
- [X] Trees
- [ ] Other

**Comment by SoftCreatR** [comment]
Nope. Umbraco is blacklisted as per own request.

**Comment by vimode** [comment]
@SoftCreatR 
Sorry to reopen this issue, I was thinking the CONTRIBUTING.md file should have the guideline about reading the blacklist/.gitignore file. 

Currently, I only see that guideline when I am about to open a PR; in the PR template which by then means the contributor has already missed reading that ignore list and then has to go back and check the ignore list before opening the PR.

**Comment by SoftCreatR** [comment]
Well, you are not able to commit your participants file, because it's excluded automatically. Then, people may just check the gitignore file :)

**Comment by vimode** [comment]
Ah I understand, it won't commit in the first place. That's a clever trick I did not think of. 

I was just thinking if its part of the contributing guideline people would not open an issue (like I did 🤦) in the first place.

**Comment by SoftCreatR** [comment]
I may update the guidelines later this day.
