### ISSUE TITLE
[ADD] New Swag Opportunity - OpenHack22

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#343]
### Organization

OpenHack'22

### Organization Website

https://code.devexperts.com/ 

### Announcement URL

https://code.devexperts.com/event/openhack22

### Description / Summary

I would appreciate some guidance here, can this be included? 

They are running their own hacktoberfest I suppose but like a hackathon with a prize fund of 10,000€. 
Participants need to make at least 3 PRs to the participating projects to qualify to win a guaranteed gift. 

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by Prakhar9450** [comment]
assign it to me

**Comment by vimode** [comment]
Actually I don't think this should be included as none of the projects listed in the [projects](https://code.devexperts.com/projects) page are labelled `hacktoberfest` on github so the contributions to those might not count towards this hacktoberfest but their own private one. 

And this repo only lists the ones which are part of the hacktobefest.com event.
