### ISSUE TITLE
[ADD] New Swag Opportunity - codedamn

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#363]
### Organization

codedamn

### Organization Website

https://codedamn.com/

### Announcement URL

https://github.com/codedamn/projects

### Description / Summary

Contribute by creating a guided project for their platform to win a Merch kit which includes tshirt and stickers

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [X] Shirt
- [ ] Socks
- [X] Stickers
- [ ] Trees
- [ ] Other

**Comment by vimode** [comment]
If anyone one wants to open a PR to add this to the list, go for it. 
If its still open when I am free after few hours, I will make a PR.

**Comment by gambhirsharma** [comment]
Can you assign this to me?
