### ISSUE TITLE
[ADD] New Swag Opportunity - Kong

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#378]
### Organization

Kong

### Organization Website

https://konghq.com/

### Announcement URL

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

### Description / Summary

If your Pull Request to kong was accepted, and it fixes a bug, adds functionality, or makes it significantly easier to use or understand Kong, you are eligible to receive the very special Contributor T-shirt! 

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [X] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [ ] Other

**Comment by vimode** [comment]
I am not sure if it should be added .

They do have a contributor T-shirt for each contribution but I assume that is something they do all year long as their repo does not have the tag `hacktoberfest` so PRs might not count towards hacktoberfest.com's PR count.

What do you think?

**Comment by crweiner** [comment]
[Kong was on the repo last year](https://github.com/benbarth/hacktoberfest-swag/tree/f463da36eecdcc5948c260545de4c7fe2eac6b35), even though I _personally_ agree with you, @vimode. Meaningful contributions there won't simultaneously count for Hacktoberfest too, but that isn't necessarily a reason to exclude them from this particular repo. I used to point people to instead contribute things like this over at[ DevSwag.io](https://github.com/swapagarwal/swag-for-dev), but that project seems dead. 😢 

No reason to exclude them if @SoftCreatR or @benbarth would like to have them on again for 2022! 😄

**Comment by SoftCreatR** [comment]
I don't think, it's necessary to add them. I'd keep out opportunities, which are not HF exklusive.
