### ISSUE TITLE
Verify with Hasura for 2019

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#38]

**Comment by crweiner** [comment]
[Hasura](hasura.io) has joined Hacktoberfest 2019 with their own swag again per [their blog post](https://blog.hasura.io/hasura-joins-hacktoberfest-2019/)!

**Comment by sandyjoshi** [comment]
@benbarth  I have raised PR for this https://github.com/benbarth/hacktoberfest-swag/pull/66
