### ISSUE TITLE
[ADD] New Swag Opportunity - StepZen

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#380]
### Organization

StepZen

### Organization Website

https://stepzen.com/

### Announcement URL

https://stepzen.com/blog/stepzen-hacktoberfest-2022

### Description / Summary

Contribute by creating new integrations or improve existing integrations. 

All contributors will receive StepZen goodies

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by viveena30** [comment]
can i try working on this issue? @vimode

**Comment by vimode** [comment]
@viveena30 Sure, go ahead make a PR.

**Comment by crweiner** [comment]
So happy to see them coming back for another year. 😀 That project is run by some very kind people. Stepzen is a great way to learn GraphQL. 👍

**Comment by vimode** [comment]
@viveena30 Are you still working on this? If you are stuck somewhere, or have trouble making a PR feel free to ask for help.

**Comment by viveena30** [comment]
Yes I'm...will make a PR today!
