### ISSUE TITLE
[ADD] New Swag Opportunity - Modtoberfest 

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#399]
### Organization

Modtoberfest 

### Organization Website

https://modtoberfest.com/ 

### Announcement URL

https://modtoberfest.com/

### Description / Summary

Modtoberfest is an annual celebration of open source projects in the Minecraft community. 
By contributing valid PRs to four different projects, you are eligible to win a prize pack which includes stickers and pins.

You have to sign up on their website to start participating. 
Not all repos are tagged `hacktoberfest` but many are. 

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [X] Stickers
- [ ] Trees
- [X] Other

**Comment by vimode** [comment]
This is an open issue for anyone to contribute.

**Comment by 2brownc** [comment]
I got an idea on how participants are added by taking a look at `hacktoberfest-swag/participants/2022/`. I would like to work on this.
