### ISSUE TITLE
Update LBRY for 2019

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#40]

**Comment by crweiner** [comment]
LBRY has plans to offer swag for Hacktoberfest per Twitter [here](https://twitter.com/jsigwart/status/1175054393541922817?s=19) and [here](https://twitter.com/jeremykauffman/status/1175053927894704129?s=19)

**Comment by crweiner** [comment]
They also just wrote a [blog post here](https://lbry.com/news/hacktoberfest-2019). :+1:
