### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by PGautam27** [benbarth/hacktoberfest-swag#403]
I mean, this is a genuine saying from my side. Cause the website is so cool. But apparently there's no favicon. Since this is a very low level issue. If I do a pull request, prolly it would go to spam or invalid. Just a word from a fellow contributor. Add a favicon, it'll be cool.

**Comment by SoftCreatR** [comment]
Thank you for your suggestion.

As of now, the "website" is just a generated GitHub page. Apart from the fact that I don't know whether favicons work here, I would completely overhaul the website and then also implement your suggestion.

**Comment by benbarth** [comment]
This is possible, no? https://stackoverflow.com/questions/35037482/favicon-with-github-pages

**Comment by SoftCreatR** [comment]
In general it is, but we're generating the page from a template. This is way more complicated, and I don't see a reason for this effort compared to the little outcome.
