### ISSUE TITLE
Improve "Support open source" section in README.md

### ISSUE THREAD

**Issue by icextreme** [benbarth/hacktoberfest-swag#410]
The [Support open source](https://github.com/benbarth/hacktoberfest-swag#support-open-source) section in README.md has two really long links that can be put into a hyperlink.  
![image](https://user-images.githubusercontent.com/74882450/195025507-b65438e4-78a1-4163-a6ed-9675bfbe7428.png)

For example,

From: 
Contribute by resolving a Hacktoberfest issue! 👉 https://github.com/search?q=label%3AHacktoberfest&state=open&type=Issues

To: 
Contribute by resolving a Hacktoberfest issue! [View all open issues here](https://github.com/search?q=label%3AHacktoberfest&state=open&type=Issues).

**Comment by icextreme** [comment]
May I take on this issue if it sounds like a good idea?

**Comment by benbarth** [comment]
That's a great idea. Right now they are also poor links from an [accessibility standpoint](https://www.accessibilityoz.com/2014/02/links-and-accessibility/). Screen readers will only read the link text so "click here" isn't the best option. Something like "You can contribute by resolving a [Hacktoberfest issue in GitHub](#example)." would be perfect. 🙌

**Comment by icextreme** [comment]
Thanks a lot!
