### ISSUE TITLE
DailyDotDev New Swag Opportunity

### ISSUE THREAD

**Issue by PGautam27** [benbarth/hacktoberfest-swag#413]
### Organization

daily.dev

### Organization Website

https://daily.dev/

### Announcement URL

https://twitter.com/dailydotdev/status/1580070255728246784

### Description / Summary

daily.dev has opened up a meme contest in this hactoberfest time. They would choose the best 10 memes that were added to the readme file and they would get swags from daily.dev.

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by vimode** [comment]
They don't have any of the official hacktoberfest labels or topics so I am not sure contributions would count towards the official event. Can someone confirm?

**Comment by PGautam27** [comment]
Hmmmm true though, it doesn't get the official hacktoberfest count. But it's yet a fun contribution.
