### ISSUE TITLE
The links should be opened up in a separate page

### ISSUE THREAD

**Issue by Rancho2002** [benbarth/hacktoberfest-swag#419]
The GitHub repositories of swags should be opened on a separate page when the user clicks on it. I want to fix this. Please assign it to me
![image](https://user-images.githubusercontent.com/92109154/196021909-1b425cc6-d540-4d67-bbde-3c0e03b6e12e.png)

**Comment by SoftCreatR** [comment]
We do not want to force the behavior of how links are opened. It should always be the user's choice.
