### ISSUE TITLE
Verify with Microsoft for 2019

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#42]

**Comment by tatendamarshall210** [comment]
I want to be verified

**Comment by benbarth** [comment]
https://github.com/benbarth/hacktoberfest-swag/blob/master/README.md

**Comment by crweiner** [comment]
> I want to be verified

If you see that Microsoft / Open@Microsoft is participating in 2019 then we'd love to have you contribute to the swag list. :smile:

**Comment by benbarth** [comment]
I don't think Microsoft is doing anything this year. Their github repo has been archived. https://github.com/microsoft/Hacktoberfest

**Comment by crweiner** [comment]
Their repo was [archived last year](https://github.com/microsoft/Hacktoberfest/commits/master) as people were submitting PRs to it and not really reading it properly. However, you are correct as it does appear that they aren't doing anything this year (or are very late to do so).
