### ISSUE TITLE
[ADD] New Swag Opportunity - Codédex 

### ISSUE THREAD

**Issue by vimode** [benbarth/hacktoberfest-swag#427]
### Organization

Codédex 

### Organization Website

https://www.codedex.io/

### Announcement URL

https://dev.to/codedex/how-to-contribute-to-hacktoberfest-with-codedex-8h9

### Description / Summary

Create project tutorials for codedex to win swag from their merch store.

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [X] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by vimode** [comment]
@sid-am-ahd935 go for it 😄

**Comment by sid-am-ahd935** [comment]
Thanks

**Comment by vimode** [comment]
I cannot assign issues, I am just a contributor like you. 

But in this repo, if an issue is open you are free to pick it up and contribute. Just make sure you read the [Contributing guidelines](https://github.com/benbarth/hacktoberfest-swag/blob/master/CONTRIBUTING.md) first.

**Comment by sid-am-ahd935** [comment]
Ohhk, thanks man
