### ISSUE TITLE
[UPD] Update existing Swag Opportunity

### ISSUE THREAD

**Issue by Luna-meili** [benbarth/hacktoberfest-swag#435]
### Organization

Meilisearch

### Organization Website

https://www.meilisearch.com

### Announcement URL

https://blog.meilisearch.com/hacktoberfest-2022-mid-october-update/

### Description / Summary

Swag: Duffle bag, webcam cover, touchscreen tool shield.
Requirements:
Submit 1 or more pull requests to qualify as a contributor. Check out the [Contributing Guidelines](https://github.com/meilisearch/.github/blob/main/Hacktoberfest_2022_contributors_guidelines.md) for more details.
How to sign up: Join the [Slack community](https://www.notion.so/6cd1509802984122ab74745f637b694f) and the [#hacktoberfest channel](https://meilicommunity.slack.com/archives/C02G1H43J2X) to connect with Meilisearch employees and for any queries.
Issues: See the list of [hacktoberfest-labeled issues](https://github.com/search?q=org%3Ameilisearch+label%3Ahacktoberfest&state=open&type=Issues).

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by SoftCreatR** [comment]
@Luna-meili The notion link doesn't seem to work, so I've removed it.

**Comment by Luna-meili** [comment]
Fantastic thanks so much for catching that : )
