### ISSUE TITLE
[UPD] Update existing Swag Opportunity - no more Hacktoberfest swag

### ISSUE THREAD

**Issue by okainov** [benbarth/hacktoberfest-swag#440]
### Organization

Hacktoberfest

### Organization Website

Hacktoberfest

### Announcement URL

https://hacktoberfest.com/about/?mkt_tok=MTEzLURUTi0yNjYAAAGOTjhWHEmREbxXJFbwsS3uknV3HB3GYZ9zSFDAhKypUchU-ou18YuLrGFRILn7MFz3PfEgzmoCrwLEilfbrXG47I6r9qMBMnAz8aVPNFxmEWU#digital-rewards

### Description / Summary

Well, so no more swag from Hacktoberfest/DigitalOcean. No more T-Shirts and other physical stuff. Should be removed from the repo description.
That's sad :(

### Swag Items

- [ ] Glasses
- [ ] Laptop
- [ ] Mug
- [ ] Shirt
- [ ] Socks
- [ ] Stickers
- [ ] Trees
- [X] Other

**Comment by hamonangann** [comment]
Hi! May I work on this?

**Comment by okainov** [comment]
@hamonangann you don't really need to ask for permission to start working on whatever :) Just hack something and make a PR and the repo owners can take a look
