### ISSUE TITLE
Update SendGrid's swag info

### ISSUE THREAD

**Issue by benbarth** [benbarth/hacktoberfest-swag#5]
New swag information is available here: https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/

**Comment by swarnava** [comment]
@benbarth  I want to take this. Where us the old swag info available which need to be replaced?

**Comment by benbarth** [comment]
The **What**, **How**, & **Additional Details** columns need to be updated now that SendGrid has made an official announcement. https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/
